[package]
name = "auth-service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlx = { version =  "0.7.1" , features = ["postgres", "runtime-tokio"]}
actix-web = "4.4.0"
dotenv = "0.15.0"
dotenv_codegen = "0.15.0"
