version: '3.9'

services:
  postgresql:
    image: postgres:16
    environment:
      POSTGRES_DB:       ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_USER_PASSWORD}
    ports:
      - "5432:5432"

  sqlx-cli:
    build:
      context: .
      dockerfile: .docker/sqlx-cli/Dockerfile
    depends_on:
      - postgresql

  auth-service-development:
    build:
      context: .
      dockerfile: .docker/auth-service/development/Dockerfile
    depends_on:
      - sqlx-cli 
    profiles:
      - development
    ports:
      - "7878:7878"

  auth-service-production:
    build:
      context: .
      dockerfile: .docker/auth-service/production/Dockerfile
    depends_on:
      - sqlx-cli 
    profiles:
      - production
    ports:
      - "7878:7878"
