name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Copy .example.env to .env
      run: cp .example.env .env

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
